'use strict';
/**
 * 通用
 */
export const CLEAR_STATUS = 'CLEAR_STATUS';

/**
 * 用户登录
 */
export const LOGGED_IN 	= 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR';
export const LOGGED_ERROR = 'LOGGED_ERROR';
export const LOGGED_DOING = 'LOGGED_DOING';
export const LOGGED_CLEAR = 'LOGGED_CLEAR';

/**
 * 注册
 */
export const REGISTER_DOING = 'REGISTER_DOING';
export const REGISTER_OK = 'REGISTER_OK';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_CLEAR = 'REGISTER_CLEAR';

/**
 * 标签操作
 */
export const GET_TAGS_OK = 'GET_TAGS_OK';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';
export const CREATE_TAG_OK = 'CREATE_TAG_OK';
export const CREATE_TAG_ERROR = 'CREATE_TAG_ERROR';
export const UPDATE_TAG_OK = 'UPDATE_TAG_OK';
export const UPDATE_TAG_ERROR = 'UPDATE_TAG_ERROR';
export const DELETE_TAG_OK = 'DELETE_TAG_OK';
export const DELETE_TAG_ERROR = 'DELETE_TAG_ERROR';

/**
 * 家庭
 */
export const INIT_OK = 'INIT_OK';
export const INIT_ERROR = 'INIT_ERROR';
export const CREATE_FAMILY_OK = 'CREATE_FAMILY_OK';
export const CREATE_FAMILY_ERROR = 'CREATE_FAMILY_ERROR';
export const UPDATE_FAMILY_OK = 'UPDATE_FAMILY_OK';
export const UPDATE_FAMILY_ERROR = 'UPDATE_FAMILY_ERROR';
export const QUIT_FAMILY_OK = 'QUIT_FAMILY_OK';
export const QUIT_FAMILY_ERROR = 'QUIT_FAMILY_ERROR';
export const GET_FAMILY_OK = 'GET_FAMILY_OK';
export const GET_FAMILY_ERROR = 'GET_FAMILY_ERROR';
export const GET_FAMILY_AND_MEMBERS_OK = 'GET_FAMILY_AND_MEMBERS_OK';
export const GET_FAMILY_AND_MEMBERS_ERROR = 'GET_FAMILY_AND_MEMBERS_ERROR';
export const GET_MEMBERS_OK = 'GET_MEMBERS_OK';
export const GET_MEMBERS_ERROR = 'GET_MEMBERS_ERROR';
export const APPLY_JOIN_FAMILY_OK = 'APPLY_JOIN_FAMILY_OK';
export const APPLY_JOIN_FAMILY_ERROR = 'APPLY_JOIN_FAMILY_ERROR';
export const GET_APPLY_JOIN_FAMILY_OK = 'GET_APPLY_JOIN_FAMILY_OK';
export const GET_APPLY_JOIN_FAMILY_ERROR = 'GET_APPLY_JOIN_FAMILY_ERROR';
export const GET_USER_APPLY_JOIN_FAMILY_OK = 'GET_USER_APPLY_JOIN_FAMILY_OK';
export const GET_USER_APPLY_JOIN_FAMILY_ERROR = 'GET_USER_APPLY_JOIN_FAMILY_ERROR';
export const DEAL_APPLY_JOIN_FAMILY_OK = 'DEAL_APPLY_JOIN_FAMILY_OK';
export const DEAL_APPLY_JOIN_FAMILY_ERROR = 'DEAL_APPLY_JOIN_FAMILY_ERROR';
export const GET_MEMBER_TAGS_OK = 'GET_MEMBER_TAGS_OK';
export const GET_MEMBER_TAGS_ERROR = 'GET_MEMBER_TAGS_ERROR';

/**
 * profile
 */
export const UPDATE_USER_INFO_OK = 'UPDATE_USER_INFO_OK';
export const UPDATE_USER_INFO_ERROR = 'UPDATE_USER_INFO_ERROR';

/**
 * 提醒
 */
export const CREATE_REMIND_OK = 'CREATE_REMIND_OK';
export const CREATE_REMIND_ERROR = 'CREATE_REMIND_ERROR';
export const REMOVE_REMIND_OK = 'REMOVE_REMIND_OK';
export const REMOVE_REMIND_ERROR = 'REMOVE_REMIND_ERROR';
export const UPDATE_REMIND_MESSAGE_OK = 'UPDATE_REMIND_MESSAGE_OK';
export const UPDATE_REMIND_MESSAGE_ERROR = 'UPDATE_REMIND_MESSAGE_ERROR';
export const DEAL_REMIND_OK = 'DEAL_REMIND_OK';
export const DEAL_REMIND_ERROR = 'DEAL_REMIND_ERROR';
export const GET_REMIND_TOME_OK = 'GET_REMIND_TOME_OK';
export const GET_REMIND_TOME_ERROR = 'GET_REMIND_TOME_ERROR';
export const GET_REMIND_ICREATE_OK = 'GET_REMIND_ICREATE_OK';
export const GET_REMIND_ICREATE_ERROR = 'GET_REMIND_ICREATE_ERROR';